/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./src/components/AppFooter.vue')['default']
    AutodartsQuickCard: typeof import('./src/components/cards/AutodartsQuickCard.vue')['default']
    ConnectionStatus: typeof import('./src/components/ConnectionStatus.vue')['default']
    CPUCard: typeof import('./src/components/cards/CPUCard.vue')['default']
    DiskCard: typeof import('./src/components/cards/DiskCard.vue')['default']
    GlassCard: typeof import('./src/components/GlassCard.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    MemoryCard: typeof import('./src/components/cards/MemoryCard.vue')['default']
    NetworkCard: typeof import('./src/components/cards/NetworkCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StatusBadge: typeof import('./src/components/StatusBadge.vue')['default']
    SystemInfoCard: typeof import('./src/components/cards/SystemInfoCard.vue')['default']
    SystemStatusBar: typeof import('./src/components/SystemStatusBar.vue')['default']
    TemperatureCard: typeof import('./src/components/cards/TemperatureCard.vue')['default']
    ToastContainer: typeof import('./src/components/ToastContainer.vue')['default']
  }
}
